### PR TITLE
Update README.ja.md

### PR DESCRIPTION
**Pull request by sugitk**
##### SUMMARY

remove unused raw/endraw tag

##### ISSUE TYPE

- Docs Pull Request

### CODE REVIEW

**Comment by IPvSean** [comment]
the raw tags are for github pages, when you render the exercises in ansible.com/network-automation

are you guys using the github pages links or just the readmes?

**Comment by sugitk** [comment]
Thank you for your review, but this rendering is wrong for me.

https://github.com/network-automation/linklight/blob/master/exercises/networking_v2/exercises/2-1-backup/README.ja.md

**Comment by sugitk** [comment]
If my understanding is correct, github pages is running on Ruby and doesn't use jinja2.  jinja2 is the framework for Python.  But I found Jekyll uses Liquid filters. I understood what you meant.

However the rendering is still wrong.  We should tell users that "please ignore those tags"..

**Comment by IPvSean** [comment]
@sugitk we still good to merge this?  I can merge if you still want this.

**Comment by sugitk** [comment]
@IPvSean sure, I appreciate it if you could merge it.  Thank you

**Pull request merged**
