### PR TITLE
Feb 11 4.0 exercises

### PR DESCRIPTION
**Pull request by jmcleroy**
##### SUMMARY

Added in tower_verify_ssl: no and ansible_ssh_user to areas that needed changes in the documentation of the exercises as noted in the commit log. 

Fixed exercise 4.0 as well as others in the 4.X family to resolve issues with completion of labs.
##### ISSUE TYPE

- Docs Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by jgholt** [comment]
I came across same issue.  Fixed with similar:
tower_verify_ssl: false 
in all sections needing it, not sure what the difference between no and false would be.  Is there a way to set this up globally so each section doesn't need it.

For:
exercises/networking_v2/exercises/4-0-tower-setup/tower_setup.yml
ssh_key_data: "/home/{{ansible_ssh_user}}/.ssh/aws-private.pem"
for this change - The directions have a note to make a manual entry.  Does
ssh_key_data: "/home/studentX/.ssh/aws-private.pem" make more sense?  I haven't tested above recommendation.

**Comment by IPvSean** [comment]
@jgholt confirmed the issue, i am not sure there is a default group for tower modules :(. i originally had a related issue here awhile ago: https://github.com/ansible/ansible/issues/47513

looks like there could be future enhancements here

**Comment by IPvSean** [comment]
@jgholt i am fixing that other exercise too with fixed inventory it will look like this now to help solve that->

```
[all:vars]
ansible_ssh_private_key_file=/home/student1/.ssh/aws-private.pem
[routers:children]
cisco

[cisco]
rtr1 ansible_host=35.182.40.234 private_ip=172.16.160.141
rtr2 ansible_host=99.79.48.101 private_ip=172.17.6.48
rtr3 ansible_host=35.183.122.121 private_ip=172.16.208.225
rtr4 ansible_host=99.79.42.172 private_ip=172.17.32.232


[cisco:vars]
ansible_user=ec2-user
ansible_network_os=ios
ansible_connection=network_cli


[dc1]
rtr1
rtr3

[dc2]
rtr2
rtr4

[hosts]
host1 ansible_host=35.182.172.117 ansible_user=ec2-user private_ip=172.17.94.153

[control]
ansible ansible_host=35.183.129.46 ansible_user=student1 private_ip=172.16.63.61
```

that way ec2-user is not being used for control node, and then you get legit location of the pem file

**Comment by IPvSean** [comment]
OK @jgholt and @jmcleroy I have a possible fix that might mean we don't have to bypass the SSL

There was a couple problems, that is why it took me a few days to figure out->
- I created an SSL intermediate cert, this logic is contained in the **aws_dns** role under the tower.yml
- I changed the exercise below to use the fqdn, I have not upstreamed this yet, @jmcleroy you are welcome to make the changes and PR it back :). 

```
git clone https://github.com/network-automation
git checkout feb6-2019
```

then run workshop normally for networking mode

try running this exercise:
```
---
- name: TOWER CONFIGURATION WITH PLAYBOOKS
  hosts: ansible
  connection: local
  become: no
  tasks:

    - name: CREATE INVENTORY
      tower_inventory:
        name: "Workshop Inventory"
        organization: Default
        tower_username: admin
        tower_password: ansible
        tower_host: "https://{{ansible_fqdn}}"

    - name: ADD CONTROL HOST INTO TOWER
      tower_host:
        name: "{{ inventory_hostname }}"
        inventory: "Workshop Inventory"
        tower_username: admin
        tower_password: ansible
        tower_host: "https://{{ansible_fqdn}}"
        variables:
          ansible_host: "{{ansible_host}}"
          ansible_user: "ec2-user"
          private_ip: "{{private_ip}}"
          ansible_connection: ssh

    - name: ADD REPO INTO TOWER - PROJECT
      tower_project:
        name: "Workshop Project"
        organization: "Default"
        scm_type: git
        scm_url: "https://github.com/network-automation/tower_workshop"
        tower_username: admin
        tower_password: ansible
        tower_host: "https://{{ansible_fqdn}}"

## make sure ansible_user corresponds to your student number
    - name: ADD CREDENTIAL INTO TOWER
      tower_credential:
        name: Workshop Credential
        ssh_key_data: "/home/{{ansible_user}}/.ssh/aws-private.pem"
        kind: ssh
        organization: Default
        tower_username: admin
        tower_password: ansible
        tower_host: "https://{{ansible_fqdn}}"

- name: ADD EACH HOST TO INVENTORY
  hosts: routers
  connection: local
  become: yes
  gather_facts: no
  tasks:

    - name: ADD HOST INTO TOWER
      tower_host:
        name: "{{ inventory_hostname }}"
        inventory: "Workshop Inventory"
        tower_username: admin
        tower_password: ansible
        tower_host: "https://{{hostvars.ansible.ansible_fqdn}}"
        variables:
          ansible_network_os: "{{ansible_network_os}}"
          ansible_host: "{{ansible_host}}"
          ansible_user: "{{ansible_user}}"
          private_ip: "{{private_ip}}"
          ansible_connection: network_cli
          ansible_become: yes
          ansible_become_method: enable
```

**Comment by IPvSean** [comment]
closing as per @jmcleroy request on internal chat system

**Comment by IPvSean** [comment]
@jgholt @jmcleroy this has been added to `devel` branch

**Pull request closed without merging**
