### PR TITLE
wrapped a conditional around Tower CERTS and DNS

### PR DESCRIPTION
**Pull request by jimbarlow**
This allows me to provision the lab without a Tower server

### CODE REVIEW

**Comment by IPvSean** [comment]
@jimbarlow is this still needed?  I think I added the functionality before I noticed the PR?  Sorry about the duplication of work.

**Comment by IPvSean** [comment]
@jimbarlow ? bump?

**Comment by IPvSean** [comment]
@jimbarlow I am going to close this PR unless I hear from you today, been over 22 days

**Comment by jimbarlow** [comment]
You are right.   You fixed it separately and this pull request should be close.

**Pull request closed without merging**
