### PR TITLE
Ipvsean/april1

### PR DESCRIPTION
**Pull request by IPvSean**
##### SUMMARY
multivendor available, this allows junos and arista to be booted

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
provisioner 

##### ADDITIONAL INFORMATION
if you do this, you will get identical booting to what is currently in all cisco lab
```
workshop_type: networking
# possible values cisco, arista, juniper or multivendor
network_type: cisco
```

### CODE REVIEW

**Comment by IPvSean** [comment]
@termlen0 @gdykeman 

the extra var file will work like this to match the special: all_cisco from previously->

```
---
# region where the nodes will live
ec2_region: us-east-2
# name prefix for all the VMs
ec2_name_prefix: CISCO-TEST
admin_password: ansible
student_total: 2
## Optional Variables
create_login_page: true
workshop_type: networking
# possible values cisco, arista, juniper or multivendor
network_type: cisco
```

can you let me know when I can merge?

**Comment by termlen0** [comment]
Didn't we decide to go with Ansible 2.8 (for tower survey dependencies)?

**Comment by IPvSean** [comment]
>Didn't we decide to go with Ansible 2.8 (for tower survey dependencies)?

I will fix this!

**Comment by IPvSean** [comment]
this closes https://github.com/network-automation/linklight/issues/230

**Pull request merged**
